name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, unlocked]

jobs:
  validation:
    name: Validating
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Node setup
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format & Lint
        run: pnpm run format-n-lint
